### ISSUE TITLE
github 和 gitee commit 不匹配

### ISSUE THREAD

**Issue by dannyZhou** [sanluan/PublicCMS-preview#4]
github 更新显示是 6 小时之前， gitee 显示两天之前。

建议将其中一个设置为 mirror  ex: https://github.com/linuxdeepin/deepin-clone

**Comment by sanluan** [comment]
抱歉，以前都是用脚本 方式、最近经常用图形界面的方式提交 遗漏了gitee
我看下这个

**Comment by dannyZhou** [comment]
https://help.github.com/articles/about-github-mirrors/ 这个可能更好理解一下。

不过我没试过，不知道能不能用。

上面那个例子可能不好理解。
