### ISSUE TITLE
[Typo] | moudle to module 

### ISSUE THREAD

**Issue by dannyZhou** [sanluan/PublicCMS-preview#5]
https://github.com/sanluan/PublicCMS-preview/blob/d96ea6b3256fe1a2a780c701a569a23a908f1ce3/publiccms-parent/publiccms-core/src/main/java/com/publiccms/logic/service/sys/SysRoleMoudleService.java#L24

**Comment by sanluan** [comment]
收到，感谢
很快会解决这个问题

**Comment by dannyZhou** [comment]
No need to say "thank you.".
All you need to do is fix this bug/issue, review codes and close this issue finally. 
In github, we don't need say any unused things.

**Comment by dannyZhou** [comment]
Don't forget write migration of database such as `PublicCMS-preview/publiccms-parent/publiccms-core/src/main/resources/initialization/upgrade/V2017.0708-V4.0.20170812.sql`

**Comment by sanluan** [comment]
写了数据库升级脚本的,注释的日期貌似写错了
